project_id = "sxggxcaanwsrufxfjbqb"

[functions.onedrive-auth]
verify_jwt = true

[functions.onedrive-callback]
verify_jwt = false

[functions.onedrive-refresh-token]
verify_jwt = false

[functions.onedrive-list-files]
verify_jwt = true

[functions.onedrive-import]
verify_jwt = true

[functions.onedrive-scheduled-import]
verify_jwt = false
